name: Template
version: '${project.version}'
api-version: '${mcApi.version}'
main: me.kruase.kotlin_plugin_template.Template
authors: [ KruASe ]

description: Template project for kotlin spigot plugins

commands:
    template:
        description: Main Template plugin command
        permission: template.help
        usage: |-
            §7Run §6/help <command> [n] §7to get page n of help
            §a/<command> §6help §a[command] §r- Show help for given command, for available commands otherwise
            §a/<command> §6reload §r- Reload config
            §cWARNING: §eCommands listed here might be unavailable for you, to get help for available commands run §a/<command> help
        aliases:
            - tmp

permissions:
    template.help:
        description: Allows to use §a/tmp §6help §r(lists only available commands)
        default: true
    template.reload:
        description: Allows to use §a/tmp §6reload
        default: op
    template.admin:
        description: Refers to §2template.reload §rby default
        default: op
        children:
            template.reload: true
